version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "firebase_*"
      - dependency-name: "cloud_firestore"
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
